name: MoGakRun CI
on:
  pull_request:
    branches: [ "main", "develop" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Debug APK
      run: bash ./gradlew assembleDebug --stacktrace
      
    - name: Build Release APK
      run: bash ./gradlew assembleRelease --stacktrace
    
    - name: 테스트용 Release APK artifact 업로드
      uses: actions/upload-artifact@v3
      with:
        name: app-release-unsigned.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        
    - name: 테스트용 Debug APK artifact 업로드
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
      
    - uses: MeilCli/slack-upload-file@v1
      with:
        slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
        channels: ${{ secrets.SLACK_CHANNEL_DEPLOY }}
        file_path: 'app/build/outputs/apk/release/app-release-unsigned.apk'
        file_name: 'app-release-unsigned.apk'
        file_type: 'apk'
        initial_comment: '🎁 release 버전 테스트 앱!'
        
    - uses: MeilCli/slack-upload-file@v1
      with:
        slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
        channels: ${{ secrets.SLACK_CHANNEL_DEPLOY }}
        file_path: 'app/build/outputs/apk/debug/app-debug.apk'
        file_name: 'app-debug.apk'
        file_type: 'apk'
        initial_comment: '🙏 debug 버전 테스트 앱!'
      
    - name: action-slack
      uses: 8398a7/action-slack@v3.8.0
      with:
        status: ${{ job.status }}
        author_name: 빌드 알림
      env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
